# Generated by Django 6.1.1 on 2026-09-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
